
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.95.16
      ansible_user: mahadev
      ansible_ssh_private_key_file: ~/.ssh/yan
      
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.95.16
      ansible_user: mahadev
      ansible_ssh_private_key_file: ~/.ssh/yan
      
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.95.16
      ansible_user: mahadev
      ansible_ssh_private_key_file: ~/.ssh/yan
